import { z } from "zod";

const wishlistSchemas = {
  lists: {
    schema: z.object({
      name: z.string(),
      description: z.string(),
      color: z.string(),
      icon: z.string(),
    }),
    raw: {
      id: "kdup91y6g8aqjah",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: "wishlist__lists",
      type: "base",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "xguongsk",
          max: 0,
          min: 0,
          name: "name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "u1ekqz95",
          max: 0,
          min: 0,
          name: "description",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "ahttl2mc",
          max: 0,
          min: 0,
          name: "color",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "bqwly2mg",
          max: 0,
          min: 0,
          name: "icon",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
      ],
      indexes: [
        "CREATE UNIQUE INDEX `idx_mZ8H0bkHRW` ON `wishlist__lists` (`name`)",
      ],
      created: "2024-11-30 05:49:37.117Z",
      updated: "2025-10-02 08:46:58.158Z",
      system: false,
    },
  },
  entries: {
    schema: z.object({
      name: z.string(),
      url: z.string(),
      price: z.number(),
      image: z.string(),
      list: z.string(),
      bought: z.boolean(),
      bought_at: z.string(),
      created: z.string(),
      updated: z.string(),
    }),
    raw: {
      id: "vm2lopnobyynu60",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: "wishlist__entries",
      type: "base",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "nnpsd0ds",
          max: 0,
          min: 0,
          name: "name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "9fzx3izf",
          max: 0,
          min: 0,
          name: "url",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "5nxmxqzt",
          max: null,
          min: null,
          name: "price",
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "2wlzozpr",
          maxSelect: 1,
          maxSize: 5242880000,
          mimeTypes: [
            "image/jpeg",
            "image/png",
            "image/svg+xml",
            "image/gif",
            "image/webp",
          ],
          name: "image",
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: null,
          type: "file",
        },
        {
          cascadeDelete: true,
          collectionId: "kdup91y6g8aqjah",
          hidden: false,
          id: "ijcfsuys",
          maxSelect: 1,
          minSelect: 0,
          name: "list",
          presentable: false,
          required: false,
          system: false,
          type: "relation",
        },
        {
          hidden: false,
          id: "bool78198511",
          name: "bought",
          presentable: false,
          required: false,
          system: false,
          type: "bool",
        },
        {
          hidden: false,
          id: "date931611388",
          max: "",
          min: "",
          name: "bought_at",
          presentable: false,
          required: false,
          system: false,
          type: "date",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [],
      created: "2024-12-22 18:28:33.028Z",
      updated: "2025-10-02 08:46:58.173Z",
      system: false,
    },
  },
  lists_aggregated: {
    schema: z.object({
      name: z.string(),
      description: z.string(),
      color: z.string(),
      icon: z.string(),
      total_count: z.number(),
      total_amount: z.any(),
      bought_count: z.number(),
      bought_amount: z.any(),
    }),
    raw: {
      id: "pbc_3764964987",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: null,
      updateRule: null,
      deleteRule: null,
      name: "wishlist__lists_aggregated",
      type: "view",
      fields: [
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text3208210256",
          max: 0,
          min: 0,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "_clone_0Rwd",
          max: 0,
          min: 0,
          name: "name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "_clone_ju1K",
          max: 0,
          min: 0,
          name: "description",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "_clone_CQDd",
          max: 0,
          min: 0,
          name: "color",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "_clone_bn0C",
          max: 0,
          min: 0,
          name: "icon",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "number1185665616",
          max: null,
          min: null,
          name: "total_count",
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "json1186288468",
          maxSize: 1,
          name: "total_amount",
          presentable: false,
          required: false,
          system: false,
          type: "json",
        },
        {
          hidden: false,
          id: "number4059607772",
          max: null,
          min: null,
          name: "bought_count",
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: "number",
        },
        {
          hidden: false,
          id: "json2718748479",
          maxSize: 1,
          name: "bought_amount",
          presentable: false,
          required: false,
          system: false,
          type: "json",
        },
      ],
      indexes: [],
      created: "2025-06-04 06:08:29.045Z",
      updated: "2025-10-02 08:46:58.186Z",
      system: false,
      viewQuery:
        "SELECT\n  wishlist__lists.id,\n  wishlist__lists.name,\n  wishlist__lists.description,\n  wishlist__lists.color,\n  wishlist__lists.icon, \n  COUNT(wishlist__entries.id) AS total_count,\n  SUM(wishlist__entries.price) AS total_amount,\n  COUNT(CASE WHEN wishlist__entries.bought = TRUE THEN 1 END) as bought_count,\n  SUM(CASE WHEN wishlist__entries.bought = TRUE THEN wishlist__entries.price ELSE 0 END) AS bought_amount\nFROM wishlist__lists\nLEFT JOIN wishlist__entries\n  ON wishlist__entries.list = wishlist__lists.id\nGROUP BY\n  wishlist__lists.id\n",
    },
  },
};

export default wishlistSchemas;
