services:
  db:
    image: postgres:16-alpine
    container_name: lifeforge-db
    restart: unless-stopped
    env_file:
      - ./env/.env.docker
    environment:
      - POSTGRES_DB=lifeforge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - '5432'
    volumes:
      - ./database/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    container_name: lifeforge-server
    restart: unless-stopped
    env_file:
      - ./env/.env.docker
    environment:
      - DOCKER_MODE=true
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lifeforge
    expose:
      - '3636'
    volumes:
      - ./modules:/lifeforge/modules
      - ./locales:/lifeforge/locales
    depends_on:
      db:
        condition: service_healthy

  client:
    build:
      context: .
      dockerfile: docker/client/Dockerfile
      args:
        - VITE_API_HOST=/api
    container_name: lifeforge-client
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      server:
        condition: service_started
