packages:
  - './apps/api'
  - './apps/web'
  - './docs'
  - './packages/*'
  - './modules/*'
  - './locales/*'
  - './tools'

allowBuilds:
  argon2: true
  core-js: true
  es5-ext: true
  esbuild: true
  fsevents: true
  sharp: true
  tesseract.js: true
  zipfile: true

minimumReleaseAgeExclude:
  - '@aws-sdk/lib-storage@3.1145.0'
  - '@aws-sdk/s3-request-presigner@3.1145.0'
