packages:
  - "./apps/api"
  - "./apps/web"
  - "./docs"
  - "./packages/*"
  - "./modules/*"
  - "./locales/*"
  - "./tools"

allowBuilds:
  core-js: true
  es5-ext: true
  esbuild: true
  fsevents: true
  sharp: true
  tesseract.js: true
  zipfile: true
