import { z } from "zod";

const passwordsSchemas = {
  entries: {
    schema: z.object({
      name: z.string(),
      website: z.string(),
      username: z.string(),
      password: z.string(),
      icon: z.string(),
      color: z.string(),
      pinned: z.boolean(),
      created: z.string(),
      updated: z.string(),
    }),
    raw: {
      id: "tgblyh0po4v8d1o",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: "passwords__entries",
      type: "base",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "f4ty6h3t",
          max: 0,
          min: 0,
          name: "name",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "erv1avc6",
          max: 0,
          min: 0,
          name: "website",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "levsseul",
          max: 0,
          min: 0,
          name: "username",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "rk3jhjg6",
          max: 0,
          min: 0,
          name: "password",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "oaez30fw",
          max: 0,
          min: 0,
          name: "icon",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "g8lfhqc5",
          max: 0,
          min: 0,
          name: "color",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "ckvtxdlg",
          name: "pinned",
          presentable: false,
          required: false,
          system: false,
          type: "bool",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [],
      system: false,
    },
  },
};

export default passwordsSchemas;
