import { z } from "zod";

const journalSchemas = {
  entries: {
    schema: z.object({
      raw: z.string(),
      summary: z.string(),
      content: z.string(),
      mood: z.any(),
      photos: z.array(z.string()),
      date: z.string(),
      title: z.string(),
      created: z.string(),
      updated: z.string(),
    }),
    raw: {
      id: "8pcs6fnobibl6pc",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: "journal__entries",
      type: "base",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "ujywwt8y",
          max: 9999999999,
          min: 0,
          name: "raw",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "7eoprtin",
          max: 0,
          min: 0,
          name: "summary",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "1daxyfje",
          max: 9999999999,
          min: 0,
          name: "content",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "wsvkpa19",
          maxSize: 2000000,
          name: "mood",
          presentable: false,
          required: false,
          system: false,
          type: "json",
        },
        {
          hidden: false,
          id: "afn5hkrt",
          maxSelect: 50,
          maxSize: 524288000,
          mimeTypes: [
            "image/jpeg",
            "image/png",
            "image/svg+xml",
            "image/gif",
            "image/webp",
          ],
          name: "photos",
          presentable: false,
          protected: true,
          required: false,
          system: false,
          thumbs: ["0x300"],
          type: "file",
        },
        {
          hidden: false,
          id: "1zax4u7k",
          max: "",
          min: "",
          name: "date",
          presentable: false,
          required: false,
          system: false,
          type: "date",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "ogmhuuc9",
          max: 0,
          min: 0,
          name: "title",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [],
      created: "2024-05-13 09:22:21.275Z",
      updated: "2025-10-02 08:46:58.625Z",
      system: false,
    },
  },
};

export default journalSchemas;
