import React from 'react'
import ModuleHeader from '../../components/general/ModuleHeader'
import { Icon } from '@iconify/react/dist/iconify.js'
import useFetch from '../../hooks/useFetch'
import APIComponentWithFallback from '../../components/general/APIComponentWithFallback'

// Generated by https://quicktype.io

export interface IDiskUsage {
  name: string
  size: string
  used: string
  avail: string
  usedPercent: string
}

function ServerStatus(): React.ReactElement {
  const [diskUsage] = useFetch<IDiskUsage[]>('disks/stats')

  return (
    <section className="flex h-full min-h-0 w-full flex-1 flex-col overflow-y-scroll px-8 sm:px-12">
      <ModuleHeader
        title="Server Status"
        desc="Monitor the server status to ensure everything is running smoothly."
      />
      <div className="mt-16 flex w-full flex-col gap-6">
        <h1 className="mb-2 flex items-center gap-2 text-2xl font-semibold">
          <Icon icon="tabler:chart-pie" className="text-3xl" />
          <span className="ml-2">Disks Usage</span>
        </h1>
        <APIComponentWithFallback data={diskUsage}>
          {typeof diskUsage !== 'string' && (
            <div className="grid gap-6 lg:grid-cols-2">
              {diskUsage.map(disk => (
                <div
                  key={disk.name}
                  className="flex flex-col gap-4 rounded-lg bg-bg-50 p-6 shadow-[4px_4px_10px_0px_rgba(0,0,0,0.05)] dark:bg-bg-900"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Icon
                        icon="streamline:hard-disk"
                        className="text-2xl text-bg-500"
                      />
                      <h2 className="text-xl text-bg-500">{disk.name}</h2>
                    </div>
                    <p className="rounded-md border border-bg-400 px-4 py-2 text-lg text-bg-400">
                      {disk.size}B
                    </p>
                  </div>
                  <div className="flex items-center justify-between">
                    <p className="text-lg text-bg-400">Used</p>
                    <p className="text-lg text-bg-400">{disk.used}B</p>
                  </div>
                  <div className="flex items-center justify-between">
                    <p className="text-lg text-bg-400">Available</p>
                    <p className="text-lg text-bg-400">{disk.avail}B</p>
                  </div>
                  <div className="mt-4 h-3 w-full overflow-hidden rounded-full border border-bg-500">
                    <div
                      className="h-full rounded-full bg-green-500"
                      style={{ width: disk.usedPercent }}
                    ></div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </APIComponentWithFallback>
      </div>
    </section>
  )
}

export default ServerStatus
