import z from 'zod'

const moviesSchemas = {
  entries: {
    schema: z.object({
      tmdb_id: z.number(),
      title: z.string(),
      original_title: z.string(),
      poster: z.string(),
      genres: z.any(),
      duration: z.number(),
      overview: z.string(),
      countries: z.any(),
      language: z.string(),
      release_date: z.string(),
      watch_date: z.string(),
      ticket_number: z.string(),
      theatre_seat: z.string(),
      theatre_showtime: z.string(),
      theatre_location: z.string(),
      theatre_location_coords: z.object({ lat: z.number(), lon: z.number() }),
      theatre_number: z.string(),
      is_watched: z.boolean()
    }),
    raw: {
      id: 'pbc_123468663',
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: 'movies__entries',
      type: 'base',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text'
        },
        {
          hidden: false,
          id: 'number1438434789',
          max: null,
          min: null,
          name: 'tmdb_id',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text724990059',
          max: 0,
          min: 0,
          name: 'title',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3834026137',
          max: 0,
          min: 0,
          name: 'original_title',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text762383602',
          max: 0,
          min: 0,
          name: 'poster',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'json2834031894',
          maxSize: 0,
          name: 'genres',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          hidden: false,
          id: 'number2254405824',
          max: null,
          min: null,
          name: 'duration',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3888370107',
          max: 0,
          min: 0,
          name: 'overview',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'json3773345755',
          maxSize: 0,
          name: 'countries',
          presentable: false,
          required: false,
          system: false,
          type: 'json'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3571151285',
          max: 0,
          min: 0,
          name: 'language',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'date4215628054',
          max: '',
          min: '',
          name: 'release_date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          hidden: false,
          id: 'date1180390397',
          max: '',
          min: '',
          name: 'watch_date',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text3973215647',
          max: 0,
          min: 0,
          name: 'ticket_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text1742151851',
          max: 0,
          min: 0,
          name: 'theatre_seat',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'date3428949474',
          max: '',
          min: '',
          name: 'theatre_showtime',
          presentable: false,
          required: false,
          system: false,
          type: 'date'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text2447088056',
          max: 0,
          min: 0,
          name: 'theatre_location',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'geoPoint4084498627',
          name: 'theatre_location_coords',
          presentable: false,
          required: false,
          system: false,
          type: 'geoPoint'
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text2138584574',
          max: 0,
          min: 0,
          name: 'theatre_number',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text'
        },
        {
          hidden: false,
          id: 'bool1180390397',
          name: 'is_watched',
          presentable: false,
          required: false,
          system: false,
          type: 'bool'
        }
      ],
      indexes: [],
      system: false
    }
  }
}

export default moviesSchemas
