export const CURRENCIES: Record<string, string[]> = {
  AFN: ['Afghani', 'AFG', '؋', 'AF'],
  ALL: ['Lek', 'ALB', 'Lek', 'AL'],
  DZD: ['Algerian Dinar', 'DZA', 'د.ج', 'DZ'],
  USD: ['US Dollar', 'USA', '$', 'US'],
  EUR: ['Euro', 'ESP', '€', 'ES'],
  AOA: ['Kwanza', 'AGO', 'Kz', 'AO'],
  XCD: ['East Caribbean Dollar', 'VCT', '$', 'VC'],
  ARS: ['Argentine Peso', 'ARG', '$', 'AR'],
  AMD: ['Armenian Dram', 'ARM', 'Դ', 'AM'],
  AWG: ['Aruban Florin', 'ABW', 'ƒ', 'AW'],
  AUD: ['Australian Dollar', 'TUV', '$', 'AU'],
  AZN: ['Azerbaijanian Manat', 'AZE', '₼', 'AZ'],
  BSD: ['Bahamian Dollar', 'BHS', '$', 'BS'],
  BHD: ['Bahraini Dinar', 'BHR', 'ب.د', 'BH'],
  BDT: ['Taka', 'BGD', '৳', 'BD'],
  BBD: ['Barbados Dollar', 'BRB', '$', 'BB'],
  BYN: ['Belarussian Ruble', 'BLR', 'Br', 'BY'],
  BZD: ['Belize Dollar', 'BLZ', 'BZ$', 'BZ'],
  XOF: ['CFA Franc BCEAO', 'TGO', 'CFA', 'TG'],
  BMD: ['Bermudian Dollar', 'BMU', '$', 'BM'],
  BTN: ['Ngultrum', 'BTN', '', 'BT'],
  INR: ['Indian Rupee', 'IND', '₹', 'IN'],
  BOB: ['Boliviano', 'BOL', '$b', 'BO'],
  BOV: ['Mvdol', 'BOL', '$b', 'BO'],
  BAM: ['Convertible Mark', 'BIH', 'KM', 'BA'],
  BWP: ['Pula', 'BWA', 'P', 'BW'],
  NOK: ['Norwegian Krone', 'NOR', 'kr', 'NO'],
  BRL: ['Brazilian Real', 'BRA', 'R$', 'BR'],
  BND: ['Brunei Dollar', 'BRN', '$', 'BN'],
  BGN: ['Bulgarian Lev', 'BGR', 'лв', 'BG'],
  BIF: ['Burundi Franc', 'BDI', '₣', 'BI'],
  CVE: ['Cabo Verde Escudo', 'CPV', '$', 'CV'],
  KHR: ['Riel', 'KHM', '៛', 'KH'],
  XAF: ['CFA Franc BEAC', 'GNB', '₣', 'GN'],
  CAD: ['Canadian Dollar', 'CAN', '$', 'CA'],
  KYD: ['Cayman Islands Dollar', 'CYM', '$', 'KY'],
  CLF: ['Unidad de Fomento', 'CHL', 'UF', 'CL'],
  CLP: ['Chilean Peso', 'CHL', '$', 'CL'],
  CNY: ['Yuan Renminbi', 'CHN', '¥', 'CN'],
  COP: ['Colombian Peso', 'COL', '$', 'CO'],
  COU: ['Unidad de Valor Real', 'COL', '$', 'CO'],
  KMF: ['Comoro Franc', 'COM', 'CF', 'KM'],
  CDF: ['Congolese Franc', 'COD', '₣', 'CD'],
  NZD: ['New Zealand Dollar', 'NIU', '$', 'NZ'],
  CRC: ['Costa Rican Colon', 'CRI', '₡', 'CR'],
  HRK: ['Kuna', 'HRV', 'kn', 'HR'],
  CUC: ['Peso Convertible', 'CUB', 'CUC$', 'CU'],
  CUP: ['Cuban Peso', 'CUB', '₱', 'CU'],
  ANG: ['Netherlands Antillean Guilder', 'ANT', 'ƒ', 'AN'],
  CZK: ['Czech Koruna', 'CZE', 'Kč', 'CZ'],
  DKK: ['Danish Krone', 'DNK', 'kr', 'DK'],
  DJF: ['Djibouti Franc', 'DJI', '₣', 'DJ'],
  DOP: ['Dominican Peso', 'DOM', 'RD$', 'DO'],
  EGP: ['Egyptian Pound', 'EGY', '£', 'EG'],
  SVC: ['El Salvador Colon', 'SLV', '$', 'SV'],
  ERN: ['Nakfa', 'ERI', 'Nfk', 'ER'],
  ETB: ['Ethiopian Birr', 'ETH', '', 'ET'],
  FKP: ['Falkland Islands Pound', 'FLK', '£', 'FK'],
  FJD: ['Fiji Dollar', 'FJI', '$', 'FJ'],
  XPF: ['CFP Franc', 'PYF', '₣', 'PF'],
  GMD: ['Dalasi', 'GMB', 'D', 'GM'],
  GEL: ['Lari', 'GEO', 'ლ', 'GE'],
  GHS: ['Ghana Cedi', 'GHA', '¢', 'GH'],
  GIP: ['Gibraltar Pound', 'GIB', '£', 'GI'],
  GTQ: ['Quetzal', 'GTM', 'Q', 'GT'],
  GBP: ['Pound Sterling', 'GBR', '£', 'GB'],
  GNF: ['Guinea Franc', 'GIN', '₣', 'GN'],
  GYD: ['Guyana Dollar', 'GUY', '$', 'GY'],
  HTG: ['Gourde', 'HTI', 'G', 'HT'],
  HNL: ['Lempira', 'HND', 'L', 'HN'],
  HKD: ['Hong Kong Dollar', 'HKG', '$', 'HK'],
  HUF: ['Forint', 'HUN', 'Ft', 'HU'],
  ISK: ['Iceland Krona', 'ISL', 'kr', 'IS'],
  IDR: ['Rupiah', 'IDN', 'Rp', 'ID'],
  XDR: ['SDR (Special Drawing Right)', 'XDR', 'SDR', 'XD'],
  IRR: ['Iranian Rial', 'IRN', '﷼', 'IR'],
  IQD: ['Iraqi Dinar', 'IRQ', 'ع.د', 'IQ'],
  ILS: ['New Israeli Sheqel', 'ISR', '₪', 'IL'],
  JMD: ['Jamaican Dollar', 'JAM', 'J$', 'JM'],
  JPY: ['Yen', 'JPN', '¥', 'JP'],
  JOD: ['Jordanian Dinar', 'JOR', 'د.ا', 'JO'],
  KZT: ['Tenge', 'KAZ', 'лв', 'KZ'],
  KES: ['Kenyan Shilling', 'KEN', 'Sh', 'KE'],
  KPW: ['North Korean Won', 'PRK', '₩', 'KP'],
  KRW: ['Won', 'KOR', '₩', 'KR'],
  KWD: ['Kuwaiti Dinar', 'KWT', 'د.ك', 'KW'],
  KGS: ['Som', 'KGZ', 'лв', 'KG'],
  LAK: ['Kip', 'LAO', '₭', 'LA'],
  LBP: ['Lebanese Pound', 'LBN', '£', 'LB'],
  LSL: ['Loti', 'LSO', 'L', 'LS'],
  ZAR: ['Rand', 'ZAF', 'R', 'ZA'],
  LRD: ['Liberian Dollar', 'LBR', '$', 'LR'],
  LYD: ['Libyan Dinar', 'LBY', 'ل.د', 'LY'],
  CHF: ['Swiss Franc', 'CHE', 'CHF', 'CH'],
  MOP: ['Pataca', 'MAC', 'P', 'MO'],
  MGA: ['Malagasy Ariary', 'MDG', '', 'MG'],
  MWK: ['Kwacha', 'MWI', 'MK', 'MW'],
  MYR: ['Malaysian Ringgit', 'MYS', 'RM', 'MY'],
  MVR: ['Rufiyaa', 'MDV', 'ރ.', 'MV'],
  MRU: ['Ouguiya', 'MRT', 'UM', 'MR'],
  MUR: ['Mauritius Rupee', 'MUS', '₨', 'MU'],
  XUA: ['ADB Unit of Account', 'XUA', 'XUA', 'XA'],
  MXN: ['Mexican Peso', 'MEX', '$', 'MX'],
  MXV: ['Mexican Unidad de Inversion (UDI)', 'MEX', 'MXV', 'MX'],
  MDL: ['Moldovan Leu', 'MDA', 'L', 'MD'],
  MNT: ['Tugrik', 'MNG', ' د.إ', 'MN'],
  MAD: ['Moroccan Dirham', 'MAR', 'د.م.', 'MA'],
  MZN: ['Mozambique Metical', 'MOZ', 'MT', 'MZ'],
  MMK: ['Kyat', 'MMR', 'K', 'MM'],
  NAD: ['Namibia Dollar', 'NAM', '$', 'NA'],
  NPR: ['Nepalese Rupee', 'NPL', '₨', 'NP'],
  NIO: ['Cordoba Oro', 'NIC', 'C$', 'NI'],
  NGN: ['Naira', 'NGA', '₦', 'NG'],
  OMR: ['Rial Omani', 'OMN', '﷼', 'OM'],
  PKR: ['Pakistan Rupee', 'PAK', '₨', 'PK'],
  PAB: ['Balboa', 'PAN', 'B/.', 'PA'],
  PGK: ['Kina', 'PNG', 'K', 'PG'],
  PYG: ['Guarani', 'PRY', 'Gs', 'PY'],
  PEN: ['Nuevo Sol', 'PER', 'S/.', 'PE'],
  PHP: ['Philippine Peso', 'PHL', '₱', 'PH'],
  PLN: ['Zloty', 'POL', 'zł', 'PL'],
  QAR: ['Qatari Rial', 'QAT', '﷼', 'QA'],
  MKD: ['Denar', 'MKD', 'ден', 'MK'],
  RON: ['Romanian Leu', 'ROU', 'lei', 'RO'],
  RUB: ['Russian Ruble', 'RUS', '₽', 'RU'],
  RWF: ['Rwanda Franc', 'RWA', '₣', 'RW'],
  SHP: ['Saint Helena Pound', 'SHN', '£', 'SH'],
  WST: ['Tala', 'WSM', 'T', 'WS'],
  STN: ['Dobra', 'STP', 'Db', 'ST'],
  SAR: ['Saudi Riyal', 'SAU', '﷼', 'SA'],
  RSD: ['Serbian Dinar', 'SRB', 'Дин.', 'RS'],
  SCR: ['Seychelles Rupee', 'SYC', '₨', 'SC'],
  SLL: ['Leone', 'SLE', 'Le', 'SL'],
  SGD: ['Singapore Dollar', 'SGP', '$', 'SG'],
  XSU: ['Sucre', 'SUR', 'S/.', 'XS'],
  SBD: ['Solomon Islands Dollar', 'SLB', '$', 'SB'],
  SOS: ['Somali Shilling', 'SOM', 'S', 'SO'],
  SSP: ['South Sudanese Pound', 'SSD', '£', 'SS'],
  LKR: ['Sri Lanka Rupee', 'LKA', '₨', 'LK'],
  SDG: ['Sudanese Pound', 'SDN', '£', 'SD'],
  SLE: ['Sierra Leone Leone', 'SLL', 'Le', 'SL'],
  SRD: ['Surinam Dollar', 'SUR', '$', 'SR'],
  SZL: ['Lilangeni', 'SWZ', 'L', 'SZ'],
  SEK: ['Swedish Krona', 'SWE', 'kr', 'SE'],
  CHE: ['WIR Euro', 'CHE', '€', 'CH'],
  CHW: ['WIR Franc', 'CHE', 'Fr.', 'CH'],
  SYP: ['Syrian Pound', 'SYR', '£', 'SY'],
  TWD: ['New Taiwan Dollar', 'TWN', 'NT$', 'TW'],
  TJS: ['Somoni', 'TJK', 'ЅМ', 'TJ'],
  TZS: ['Tanzanian Shilling', 'TZA', 'Sh', 'TZ'],
  THB: ['Baht', 'THA', '฿', 'TH'],
  TOP: ['Pa’anga', 'TON', 'T$', 'TO'],
  TTD: ['Trinidad and Tobago Dollar', 'TTO', 'TT$', 'TT'],
  TND: ['Tunisian Dinar', 'TUN', 'د.ت', 'TN'],
  TRY: ['Turkish Lira', 'TUR', '₺', 'TR'],
  TMT: ['Turkmenistan New Manat', 'TKM', 'm', 'TM'],
  UGX: ['Uganda Shilling', 'UGA', 'Sh', 'UG'],
  UAH: ['Hryvnia', 'UKR', '₴', 'UA'],
  AED: ['UAE Dirham', 'ARE', ' د.إ', 'AE'],
  USN: ['US Dollar (Next day)', 'USA', 'US$', 'US'],
  UYI: ['Uruguay Peso en Unidades Indexadas (URUIURUI)', 'URY', '$U', 'UY'],
  UYU: ['Peso Uruguayo', 'URY', '$U', 'UY'],
  UZS: ['Uzbekistan Sum', 'UZB', 'лв', 'UZ'],
  VUV: ['Vatu', 'VUT', 'Vt', 'VU'],
  VEF: ['Bolivar', 'VEN', 'Bs', 'VE'],
  VED: ['Bolivar', 'VEN', 'Bs', 'VE'],
  VND: ['Dong', 'VNM', '₫', 'VN'],
  YER: ['Yemeni Rial', 'YEM', '﷼', 'YE'],
  ZMW: ['Zambian Kwacha', 'ZMB', 'ZK', 'ZM'],
  ZWL: ['Zimbabwe Dollar', 'ZWE', '$', 'ZW'],
  FOK: ['Faroese Krona', 'FRO', 'kr', 'FO'],
  GGP: ['Guernsey Pound', 'GGY', '£', 'GG'],
  IMP: ['Manx Pound', 'IMN', '£', 'IM'],
  JEP: ['Jersey Pound', 'JEY', '£', 'JE'],
  KID: ['Kitts and Nevis Dollar', 'KNA', ' $', 'KN'],
  TVD: ['Tuvalu Dollar', 'TUV', '$', 'TV'],
  VES: ['Venezuelan Bolívar', 'VEN', 'Bs', 'VE']
}
