import { z } from "zod";

const momentVaultSchemas = {
  entries: {
    schema: z.object({
      type: z.enum(["text", "audio", "video", "photos", ""]),
      file: z.array(z.string()),
      content: z.string(),
      transcription: z.string(),
      created: z.string(),
      updated: z.string(),
    }),
    raw: {
      id: "pbc_2203688272",
      listRule: '@request.auth.id != ""',
      viewRule: '@request.auth.id != ""',
      createRule: '@request.auth.id != ""',
      updateRule: '@request.auth.id != ""',
      deleteRule: '@request.auth.id != ""',
      name: "moment_vault__entries",
      type: "base",
      fields: [
        {
          autogeneratePattern: "[a-z0-9]{15}",
          hidden: false,
          id: "text3208210256",
          max: 15,
          min: 15,
          name: "id",
          pattern: "^[a-z0-9]+$",
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: "text",
        },
        {
          hidden: false,
          id: "select2363381545",
          maxSelect: 1,
          name: "type",
          presentable: false,
          required: false,
          system: false,
          type: "select",
          values: ["text", "audio", "video", "photos"],
        },
        {
          hidden: false,
          id: "file2359244304",
          maxSelect: 99,
          maxSize: 9999999999,
          mimeTypes: [],
          name: "file",
          presentable: false,
          protected: false,
          required: false,
          system: false,
          thumbs: [],
          type: "file",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text4274335913",
          max: 0,
          min: 0,
          name: "content",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          autogeneratePattern: "",
          hidden: false,
          id: "text849144196",
          max: 0,
          min: 0,
          name: "transcription",
          pattern: "",
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: "text",
        },
        {
          hidden: false,
          id: "autodate2990389176",
          name: "created",
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: "autodate",
        },
        {
          hidden: false,
          id: "autodate3332085495",
          name: "updated",
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: "autodate",
        },
      ],
      indexes: [],
      created: "2025-02-20 12:08:45.463Z",
      updated: "2025-10-02 08:46:58.644Z",
      system: false,
    },
  },
};

export default momentVaultSchemas;
