export const METAR_ICONS = {
  SKC: 'wi-day-sunny',
  CLR: 'wi-day-sunny',
  FEW: 'wi-day-cloudy',
  SCT: 'wi-day-cloudy',
  BKN: 'wi-day-cloudy',
  OVC: 'wi-day-cloudy',
  NSC: 'wi-day-sunny',
  CAVOK: 'wi-day-sunny',
  VV: 'wi-day-sunny',
  BR: 'wi-day-fog',
  FG: 'wi-day-fog',
  FU: 'wi-day-fog',
  HZ: 'wi-day-fog',
  DU: 'wi-day-fog',
  SA: 'wi-day-fog',
  VA: 'wi-day-fog',
  RA: 'wi-day-rain',
  DZ: 'wi-day-rain',
  SN: 'wi-day-snow',
  SG: 'wi-day-snow',
  IC: 'wi-day-snow',
  PL: 'wi-day-snow',
  GR: 'wi-day-snow',
  GS: 'wi-day-snow',
  PE: 'wi-day-snow',
  UP: 'wi-day-snow',
  TS: 'wi-day-thunderstorm',
  SH: 'wi-day-showers',
  FZ: 'wi-day-snow',
  DS: 'wi-day-fog',
  SS: 'wi-dust',
  PO: 'wi-day-fog',
  SQ: 'wi-day-fog',
  FC: 'wi-day-fog'
}

export const METAR_CODES = {
  '+': 'Heavy',
  '-': 'Light',
  SKC: 'Sky clear',
  CLR: 'No significant cloud',
  FEW: 'Few clouds',
  SCT: 'Scattered clouds',
  BKN: 'Broken clouds',
  OVC: 'Overcast',
  NSC: 'No significant cloud',
  CAVOK: 'Ceiling and visibility okay',
  VV: 'Vertical visibility',
  BR: 'Mist',
  FG: 'Fog',
  FU: 'Smoke',
  HZ: 'Haze',
  DU: 'Widespread dust',
  SA: 'Sand',
  VA: 'Volcanic ash',
  RA: 'Rain',
  DZ: 'Drizzle',
  SN: 'Snow',
  SG: 'Snow grains',
  IC: 'Ice crystals',
  PL: 'Ice pellets',
  GR: 'Hail',
  GS: 'Small hail and/or snow pellets',
  PE: 'Ice pellets',
  UP: 'Unknown precipitation',
  TS: 'Thunderstorm',
  SH: 'Showers',
  FZ: 'Freezing',
  DS: 'Dust storm',
  SS: 'Sandstorm',
  PO: 'Well-developed dust/sand whirls',
  SQ: 'Squall',
  FC: 'Funnel cloud (tornado or waterspout)',
  VC: 'In the vicinity'
}
